
module.exports = {
    $addFields: (content) => ({ $addFields: content }),
    $bucket: (content) => ({ $bucket: content }),
    $bucketAuto: (content) => ({ $bucketAuto: content }),
    $collStats: (content) => ({ $collStats: content }),
    $count: (content) => ({ $count: content }),
    $currentOp: (content) => ({ $currentOp: content }),
    $facet: (content) => ({ $facet: content }),
    $geoNear: (content) => ({ $geoNear: content }),
    $graphLookup: (content) => ({ $graphLookup: content }),
    $group: (content) => ({ $group: content }),
    $indexStats: (content) => ({ $indexStats: content }),
    $limit: (content) => ({ $limit: content }),
    $listLocalSessions: (content) => ({ $listLocalSessions: content }),
    $listSessions: (content) => ({ $listSessions: content }),
    $lookup: (content) => ({ $lookup: content }),
    $match: (content) => ({ $match: content }),
    $out: (content) => ({ $out: content }),
    $project: (content) => ({ $project: content }),
    $redact: (content) => ({ $redact: content }),
    $replaceRoot: (content) => ({ $replaceRoot: content }),
    $sample: (content) => ({ $sample: content }),
    $skip: (content) => ({ $skip: content }),
    $sort: (content) => ({ $sort: content }),
    $sortByCount: (content) => ({ $sortByCount: content }),
    $unwind: (content) => ({ $unwind: content }),
};
